Repository iamwhoamianamy/flop.net, pull requests merged in 2022-03, with the labels that each got.

#53 GUI: некоторые изменения интерфейса
  flop.net/App.xaml
  flop.net/App.xaml.cs
  flop.net/Images/redo.png
  flop.net/Images/undo.png
  flop.net/Properties/Settings.Designer.cs
  flop.net/Styles/MenuButton.xaml
  flop.net/View/IGraphic.cs
  flop.net/View/MainWindow.xaml
  flop.net/View/MainWindow.xaml.cs
  flop.net/ViewModel/Models/DrawingParameters.cs
  flop.net/flop.net.csproj
Labels: enhancement

#51 Refactor class Figure
  flop.net/View/MainWindow.xaml
  flop.net/View/MainWindow.xaml.cs
  flop.net/ViewModel/MainWindowVM.cs
  flop.net/ViewModel/Models/DrawingParameters.cs
  flop.net/ViewModel/Models/Figure.cs
Labels: enhancement

#58 Удалил ненужные перечисления
  flop.net/ViewModel/Enums/TypesFill.cs
  flop.net/ViewModel/Enums/TypesStroke.cs
  flop.net/ViewModel/Models/DrawingParameters.cs
  flop.net/flop.net.csproj
Labels: enhancement

#65 Пересоздала проект с тестами на .NET Framework 4.8
  flop.net.Tests/App.config
  flop.net.Tests/Properties/AssemblyInfo.cs
  flop.net.Tests/flop.net.Tests.csproj
  flop.net.Tests/packages.config
  flop.net.sln
Labels: enhancement

#50 Добавил шаблон класса слоя
  flop.net/View/MainWindow.xaml
  flop.net/View/MainWindow.xaml.cs
  flop.net/ViewModel/MainWindowVM.cs
  flop.net/ViewModel/Models/Layer.cs
  flop.net/flop.net.csproj
Labels: enhancement

#64 Добавлен в фабрику полигонов метод, создающий эллипс
  flop.net.Tests/PolygonBuilderTest.cs
  flop.net.Tests/flop.net.Tests.csproj
  flop.net.Tests/packages.config
  flop.net/Model/PolygonBuilder.cs
Labels: review

#63 Добавлена перегрузка метода CreateTriangle для 3-х точек
  flop.net.Tests/PolygonBuilderTest.cs
  flop.net.Tests/flop.net.Tests.csproj
  flop.net/Model/PolygonBuilder.cs
Labels: review

#87 Разделить классы по файлам
  flop.net/ViewModel/MainWindowVM.cs
  flop.net/ViewModel/UserCommands.cs
  flop.net/flop.net.csproj
Labels: enhancement

#84 79 создать свойство для хранения создаваемой фигуры
  flop.net/Model/DrawingParameters.cs
  flop.net/Model/Figure.cs
  flop.net/Model/Layer.cs
  flop.net/Model/PolygonBuilder.cs
  flop.net/View/IGraphic.cs
  flop.net/ViewModel/MainWindowVM.cs
  flop.net/flop.net.csproj
Labels: enhancement

#94 Добавлено автоматическое вычисление числа точек для построения эллипса
  flop.net/Model/PolygonBuilder.cs
Labels: testing

#97 Пересоздала проект с тестами
  flop.net.Tests/Geometry/PolygonBuilderTests.cs
  flop.net.Tests/PolygonBuilderTest.cs
  flop.net.Tests/Program.cs
  flop.net.Tests/Properties/AssemblyInfo.cs
  flop.net.Tests/UnitTest1.cs
  flop.net.Tests/flop.net.Tests.csproj
  flop.net.sln
Labels: review

#99 Исправлен расчет высоты и ширины эллипса
  flop.net.Tests/Geometry/PolygonBuilderTests.cs
  flop.net/Model/PolygonBuilder.cs
Labels: review

#101 Переделан класс JsonSaver для сериализации контейнера со слоями.
  flop.net/Save/JsonSaver.cs
  flop.net/flop.net.csproj
Labels: enhancement

#102 78 сделать обработчики кнопок создания фигур
  flop.net/Enums/FigureCreationMode.cs
  flop.net/Enums/ViewMode.cs
  flop.net/View/IGraphic.cs
  flop.net/View/MainWindow.xaml
  flop.net/View/MainWindow.xaml.cs
  flop.net/ViewModel/MainWindowVM.cs
  flop.net/flop.net.csproj
Labels: enhancement

#85 Add property ActiveFigure and command SetActiveFigure
  flop.net.Tests/ViewModel/MainWindowVMTests.cs
  flop.net.Tests/flop.net.Tests.csproj
  flop.net/ViewModel/MainWindowVM.cs
Labels: enhancement, testing

#83 73 geometry circumscribing rectangle
  flop.net.Tests/Geometry/BoundingBoxTests.cs
  flop.net.Tests/Geometry/PolygonBuilderTest.cs
  flop.net.Tests/flop.net.Tests.csproj
  flop.net/Model/IGeometric.cs
  flop.net/Model/Polygon.cs
  flop.net/Model/PolygonBuilder.cs
Labels: testing

#72 25 polygon isin
  flop.net.Tests/Geometry/PolygonIsInTest.cs
  flop.net.Tests/flop.net.Tests.csproj
  flop.net/Model/Polygon.cs
  flop.net/View/MainWindow.xaml.cs
Labels: review

#113 Добавлен необязательный параметр scalePoint в Scale, обозначающий точ…
  flop.net/Model/IGeometric.cs
  flop.net/Model/Polygon.cs
Labels: review

#125 124 geometry rotation angle
  flop.net/Model/Polygon.cs
Labels: review

#126 111 geometry rectangle
  flop.net/Model/IGeometric.cs
  flop.net/Model/Polygon.cs
  flop.net/Model/Rectangle.cs
  flop.net/flop.net.csproj
Labels: review

#127 Выбор темы приложения
  flop.net/View/MainWindow.xaml
  flop.net/View/MainWindow.xaml.cs
  flop.net/ViewModel/MainWindowVM.cs
Labels: enhancement

#129 128 geometry canvas axis hotfix
  flop.net/Model/Polygon.cs
  flop.net/Model/PolygonBuilder.cs
Labels: review

#134 Сделан класс Trully observable collection
  flop.net/Model/DrawingParameters.cs
  flop.net/Model/Figure.cs
  flop.net/Model/Layer.cs
  flop.net/Model/TrulyObservableCollection.cs
  flop.net/ViewModel/MainWindowVM.cs
  flop.net/flop.net.csproj
Labels: enhancement

#133 Сделать команду для сохранения слоев
  flop.net/View/MainWindow.xaml.cs
  flop.net/ViewModel/MainWindowVM.cs
Labels: enhancement

#135 Сделал тесты для метода Move
  flop.net.Tests/Geometry/PolygonMoveTests.cs
  flop.net.Tests/flop.net.Tests.csproj
Labels: testing, review

#137 Added save to png
  flop.net/Save/PngSaver.cs
  flop.net/Save/SaveParameters.cs
  flop.net/Save/SvgSaver.cs
  flop.net/View/MainWindow.xaml.cs
  flop.net/ViewModel/MainWindowVM.cs
  flop.net/flop.net.csproj
Labels: enhancement

#138 Проверить повороты фигур
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .mailmap
  AUTHORS.md
  flop.net.Tests/Geometry/PolygonTests.cs
  flop.net.Tests/flop.net.Tests.csproj
Labels: testing, review

#144 Баг исправлен. Теперь при обратном вращении вращаются точки прямоугол…
  flop.net/Model/Polygon.cs
Labels: review

#150 Добавлена реализация метода AddPoint для замкнутой фигуры.
  flop.net/Model/Polygon.cs
Labels: review

#151 1) Разделен BoundingBox вращающийся и не вращающийся.
  flop.net/Model/IGeometric.cs
  flop.net/Model/Polygon.cs
Labels: review

#155 Тесты для проверки масштабирования треугольника, прямоугольника и эллипса
  flop.net.Tests/Geometry/PolygonTests.cs
Labels: testing, review

#162 Сделаны перемещение и масштабирование с помощью GUI
  flop.net/Model/Rectangle.cs
  flop.net/Model/TrulyObservableCollection.cs
  flop.net/View/MainWindow.xaml
  flop.net/View/MainWindow.xaml.cs
  flop.net/View/MultiplyConverter.cs
  flop.net/View/ThumbsBox.cs
  flop.net/ViewModel/MainWindowVM.cs
  flop.net/flop.net.csproj
Labels: enhancement, important

#164 Сделана команда, которая запоминает DP активной фигуры
  flop.net/ViewModel/MainWindowVM.cs
Labels: enhancement

#165 Добавлен конструктор для полилинии, добавлена реализация метода AddPo…
  flop.net/Model/Polygon.cs
  flop.net/Model/PolygonBuilder.cs
Labels: review

#170 Сделала тесты на создание и запись для файлов svg
  flop.net.Tests/Save/Answers/SvgAnswer.txt
  flop.net.Tests/Save/SvgSaverTests.cs
  flop.net.Tests/flop.net.Tests.csproj
Labels: testing, review

#166 Geometry move point
  flop.net/Model/IGeometric.cs
  flop.net/Model/Polygon.cs
Labels: review

#174 hotfix Opacity
  flop.net/View/MainWindow.xaml
  flop.net/ViewModel/MainWindowVM.cs
Labels: bug

#176 158 сделать методы для горизонтального и вертикального отражения фигуры в polygon
  flop.net/Model/IGeometric.cs
  flop.net/Model/Polygon.cs
Labels: review

#177 175 сделать тесты для сохранения в pdf и png форматах
  flop.net.Tests/Geometry/PolygonBuilderTest.cs
  flop.net.Tests/Save/Answers/SvgAnswerEllipse.txt
  flop.net.Tests/Save/Answers/SvgAnswerRectangle.txt
  flop.net.Tests/Save/Answers/SvgAnswerTriangle.txt
  flop.net.Tests/Save/PdfSaverTests.cs
  flop.net.Tests/Save/SvgSaverTests.cs
  flop.net.Tests/flop.net.Tests.csproj
Labels: testing, review

#178 Scale ellipse hotfix
  flop.net/Model/Ellipse.cs
  flop.net/Model/PolygonBuilder.cs
  flop.net/flop.net.csproj
Labels: review
